[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hanetoolpy"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
hanetoolpy = "hanetoolpy.main:main"
